[tool.poetry]
name = "prefect_workshop"
version = "0.1.0"
description = ""
authors = ["Richard <richard.kyle@spark.co.nz>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
prefect = "^3.0.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
